site_name: Kaguya-samaWannaMeAC-Wiki

# repo_name: 'Kaguya-samaWannaMeAC'
# repo_url: 'https://github.com/Kaguya-samaWannaMeAC/Kaguya-samaWannaMeAC-Wiki'

theme:
  name: material
  palette:
    primary: 'White'
    accent: 'Pink'
  features:
    - tabs
  language: 'zh'
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'
  logo: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # - 'js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - 首页: index.md
  - 比赛记录: 
    - 比赛模板: contest/template.md
    - XIX SPb Div1 2020.12.16: contest/XIX SPb Div1 2020.12.16.md
    - SEERC 2016 2020.05.10: contest/SEERC2016 2020.05.10.md
    - 2017-2018 NEERC Moscow 2020.05.17: contest/2017-2018 NEERC Moscow 2020.05.17.md
    - 2009-2010 NEERC Western 2020.05.24: contest/2009-2010 NEERC Western 2020.05.24.md
  
