site_name: Kaguya-samaWannaMeAC-Wiki

# repo_name: 'Kaguya-samaWannaMeAC'
# repo_url: 'https://github.com/Kaguya-samaWannaMeAC/Kaguya-samaWannaMeAC-Wiki'

theme:
  name: material
  palette:
    primary: 'White'
    accent: 'Pink'
  features:
    - tabs
  language: 'zh'
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'
  logo: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - 首页: index.md
  - 比赛记录: 
    - 比赛模板: contest/template.md
    - 2020.05.10 SEERC 2016: contest/2020-05-10 SEERC2016.md
    - 2020.05.17 2017-2018 NEERC Moscow: contest/2020-05-17 2017-2018 NEERC Moscow.md
    - 2020.05.24 2009-2010 NEERC Western: contest/2020-05-24 2009-2010 NEERC Western.md
    - 2020.07.12 2020牛客暑期多校第一场: contest/2020-07-12 2020牛客暑期多校第一场.md
    - 2020.07.13 2020牛客暑期多校第二场: contest/2020-07-13 2020牛客暑期多校第二场.md
    - 2020.07.18 2020牛客暑期多校第三场: contest/2020-07-18 2020牛客暑期多校第三场.md
    - 2020.07.20 2020牛客暑期多校第四场: contest/2020-07-20 2020牛客暑期多校第四场.md
    - 2020.07.22 2020HDU暑期多校第一场: contest/2020-07-22 2020HDU暑期多校第一场.md
    - 2020.07.23 2020-2021 BUAA Training 1: contest/2020-07-23 2020-2021 BUAA ICPC Team Supplementary Training 01.md
    - 2020.07.25 2020牛客暑期多校第五场: contest/2020-07-25 2020牛客暑期多校第五场.md
    - 2020.07.20 2020牛客暑期多校第六场: contest/2020-07-27 2020牛客暑期多校第六场.md
    - 2020.07.29 2020HDU暑期多校第二场: contest/2020-07-29 2020HDU暑期多校第二场.md
    - 2020.08.01 2020牛客暑期多校第七场: contest/2020-08-01 2020牛客暑期多校第七场.md
    - 2020.08.03 2020牛客暑期多校第八场: contest/2020-08-03 2020牛客暑期多校第八场.md
    - 2020.12.16 XIX SPb Div1: contest/2020-12-16 XIX SPb Div1.md
  
